// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	linktrailers "movie/businesses/linktrailers"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, domain
func (_m *UseCase) Create(ctx context.Context, domain *linktrailers.Domain) (linktrailers.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 linktrailers.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *linktrailers.Domain) linktrailers.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(linktrailers.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *linktrailers.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, idLink, domain
func (_m *UseCase) Delete(ctx context.Context, idLink int, domain *linktrailers.Domain) error {
	ret := _m.Called(ctx, idLink, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *linktrailers.Domain) error); ok {
		r0 = rf(ctx, idLink, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUrl provides a mock function with given fields: ctx, domain
func (_m *UseCase) GetUrl(ctx context.Context, domain *linktrailers.Domain) (linktrailers.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 linktrailers.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *linktrailers.Domain) linktrailers.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(linktrailers.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *linktrailers.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, idLink, domain
func (_m *UseCase) Update(ctx context.Context, idLink int, domain *linktrailers.Domain) error {
	ret := _m.Called(ctx, idLink, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *linktrailers.Domain) error); ok {
		r0 = rf(ctx, idLink, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
